// <auto-generated />
using System;
using CashFlow.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CashFlow.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240805124008_correctCategory")]
    partial class correctCategory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CashFlow.DataBase.Entities.Budget", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MoneyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("MoneyId");

                    b.ToTable("Budgets");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Category", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Name");

                    b.ToTable("Caterogies");

                    b.HasData(
                        new
                        {
                            Name = "Comida y Bebida"
                        },
                        new
                        {
                            Name = "Compras"
                        },
                        new
                        {
                            Name = "Vivienda"
                        },
                        new
                        {
                            Name = "Transporte"
                        },
                        new
                        {
                            Name = "Vehiculos"
                        },
                        new
                        {
                            Name = "Vida y entretenimiento"
                        },
                        new
                        {
                            Name = "Comunicaciones"
                        },
                        new
                        {
                            Name = "Gastos financieros"
                        },
                        new
                        {
                            Name = "Inversiones"
                        },
                        new
                        {
                            Name = "Trabajo"
                        },
                        new
                        {
                            Name = "Otros"
                        });
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Expense", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MoneyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryName");

                    b.HasIndex("MoneyId");

                    b.ToTable("Expenses");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MoneyId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MoneyId");

                    b.ToTable("Income");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Money", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Rest")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Moneys");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Budget", b =>
                {
                    b.HasOne("CashFlow.DataBase.Entities.Category", "Category")
                        .WithMany("budgets")
                        .HasForeignKey("CategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashFlow.DataBase.Entities.Money", "Money")
                        .WithMany("Budgets")
                        .HasForeignKey("MoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Money");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Expense", b =>
                {
                    b.HasOne("CashFlow.DataBase.Entities.Category", "Category")
                        .WithMany("expenses")
                        .HasForeignKey("CategoryName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CashFlow.DataBase.Entities.Money", "Money")
                        .WithMany("Expenses")
                        .HasForeignKey("MoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Money");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Income", b =>
                {
                    b.HasOne("CashFlow.DataBase.Entities.Money", "Money")
                        .WithMany("Incomes")
                        .HasForeignKey("MoneyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Money");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Money", b =>
                {
                    b.HasOne("CashFlow.DataBase.Entities.User", "User")
                        .WithOne("TotalMoney")
                        .HasForeignKey("CashFlow.DataBase.Entities.Money", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Category", b =>
                {
                    b.Navigation("budgets");

                    b.Navigation("expenses");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.Money", b =>
                {
                    b.Navigation("Budgets");

                    b.Navigation("Expenses");

                    b.Navigation("Incomes");
                });

            modelBuilder.Entity("CashFlow.DataBase.Entities.User", b =>
                {
                    b.Navigation("TotalMoney")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
